leftnav:
- identifier: 8488bde4-6909-b726-a411-abeee039ef1a
  name: Syllabus
  pageRef: /pages/syllabus/
  weight: 10
- identifier: d12ae057-a5dc-4ea0-8af4-cf62abda0530
  name: Online Textbook
  pageRef: /pages/online-textbook
  weight: 20
- identifier: 8897a3b7-567f-b552-81b3-2f8a1de7b53b
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 14fc866f-f60f-c69f-19eb-4338bbc87675
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: f8da8d9b-f6a4-78e6-808b-aa7e6aa62306
  name: 'Review: Vectors'
  pageRef: /pages/review-vectors/
  weight: 50
- identifier: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  name: 'Week 1: Kinematics'
  pageRef: /pages/week-1-kinematics/
  weight: 60
- identifier: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  name: 'Week 2: Newton''s Laws'
  pageRef: /pages/week-2-newtons-laws/
  weight: 70
- identifier: 3c7d357c-bb95-e729-679b-539d23714ede
  name: 'Week 3: Circular Motion'
  pageRef: /pages/week-3-circular-motion/
  weight: 80
- identifier: 919a2c50-6eb4-551d-940b-b0dbab2356f0
  name: 'Week 4: Drag Forces, Constraints and Continuous Systems'
  pageRef: /pages/week-4-drag-forces-constraints-and-continuous-systems/
  weight: 90
- identifier: c1168b62-a27d-cf9f-3fe2-550af1ed72f5
  name: 'Week 5: Momentum and Impulse'
  pageRef: /pages/week-5-momentum-and-impulse/
  weight: 100
- identifier: 28d93f13-f552-de72-9aab-415b7158be8e
  name: 'Week 6: Continuous Mass Transfer'
  pageRef: /pages/week-6-continuous-mass-transfer/
  weight: 110
- identifier: 1099b766-7930-f7e5-1ccc-c80d63899c02
  name: 'Week 7: Kinetic Energy and Work'
  pageRef: /pages/week-7-kinetic-energy-and-work/
  weight: 120
- identifier: 13949981-43ef-cc49-3f7c-98265cfbd3ae
  name: 'Week 8: Potential Energy and Energy Conservation'
  pageRef: /pages/week-8-potential-energy-and-energy-conservation/
  weight: 130
- identifier: bc33ee80-c8fd-90e4-dfda-7092ddd24879
  name: 'Week 9: Collision Theory'
  pageRef: /pages/week-9-collision-theory/
  weight: 140
- identifier: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  name: 'Week 10: Rotational Motion'
  pageRef: /pages/week-10-rotational-motion/
  weight: 150
- identifier: d36579bd-7dfc-b71f-7617-8b4b8d45c312
  name: 'Week 11: Angular Momentum'
  pageRef: /pages/week-11-angular-momentum/
  weight: 160
- identifier: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  name: 'Week 12: Rotations and Translation - Rolling'
  pageRef: /pages/week-12-rotations-and-translation-rolling/
  weight: 170
- identifier: 63b200b4-6b93-d532-b387-9a3d37067265
  name: About the Team
  pageRef: /pages/syllabus/about-the-team
  parent: 8488bde4-6909-b726-a411-abeee039ef1a
  weight: 10
- identifier: 649cf3cc-8fa4-f358-b8d5-87dc9811786f
  name: 'Lesson 0: Vectors [0.1 - 0.6]'
  pageRef: /pages/review-vectors/0-1-vectors-vs--scalars
  parent: f8da8d9b-f6a4-78e6-808b-aa7e6aa62306
  weight: 10
- identifier: 97fba9f7-6d6d-798d-05e2-c866432eef63
  name: Week 1 Introduction
  pageRef: /pages/week-1-kinematics/week-1-introduction
  parent: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  weight: 10
- identifier: 1e6eee21-47cf-c898-259a-beb1bbe8626d
  name: 'Lesson 1: 1D Kinematics - Position and Velocity [1.1-1.7]'
  pageRef: /pages/week-1-kinematics/1-1-coordinate-systems-and-unit-vectors-in-1d-position-vector-in-1d
  parent: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  weight: 20
- identifier: 044c013e-e454-a053-8e54-74d995c51062
  name: 'Lesson 2: 1D Kinematics - Acceleration [2.1-2.5]'
  pageRef: /pages/week-1-kinematics/2-1-introduction-to-acceleration
  parent: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  weight: 30
- identifier: 355b5de2-6116-b582-7ce8-833ba051ad9f
  name: 'Lesson 3: 2D Kinematics [3.1-3.5]'
  pageRef: /pages/week-1-kinematics/3-1-coordinate-system-and-position-vector-in-2d
  parent: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  weight: 40
- identifier: ee2f73c8-bddd-e169-e39c-a455f12469aa
  name: Week 1 Worked Examples [PS.1.1-PS.1.5]
  pageRef: /pages/week-1-kinematics/ps.1.1-three-questions-before-starting/
  parent: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  weight: 50
- identifier: bcc90f49-f292-0609-8ad9-efd22acf9676
  name: Problem Set 1
  pageRef: /pages/week-1-kinematics/problem-set-1
  parent: 63e325a7-80c7-9e35-2fb5-bddb9b8b2c6a
  weight: 60
- identifier: eff85fab-7e8f-a0b8-8e6d-207da8a7b2d5
  name: Week 2 Introduction
  pageRef: /pages/week-2-newtons-laws/week-2-introduction
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 10
- identifier: aa795ebd-f4fa-443e-b69f-1f033e83a93f
  name: 'Lesson 4: Newton''s Laws of Motion [4.1-4.4]'
  pageRef: /pages/week-2-newtons-laws/4-1-newtons-first-and-second-laws
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 20
- identifier: 5a03ea05-c949-6dde-2e74-b2e89df96295
  name: 'Lesson 5: Gravity [5.1-5.3]'
  pageRef: /pages/week-2-newtons-laws/5-1-universal-law-of-gravitation
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 30
- identifier: d1968a61-bae6-0ee9-89bc-bb1908425c38
  name: 'Lesson 6: Contact Forces [6.1-6.2]'
  pageRef: /pages/week-2-newtons-laws/6-1-contact-forces
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 40
- identifier: e5a52811-e169-8a0e-86ed-89dc040ff7ce
  name: 'Lesson 7: Tension and Springs [7.1-7.4]'
  pageRef: /pages/week-2-newtons-laws/7-1-pushing-pulling-and-tension
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 50
- identifier: 9645d508-f2f5-91c3-d286-68b53745d928
  name: 'Deep Dive: Friction [DD 1.1]'
  pageRef: /pages/week-2-newtons-laws/dd-1-1-friction-at-the-nanoscale
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 60
- identifier: 049199c2-b750-bf9b-0743-89e653cf5020
  name: Week 2 Worked Examples [PS.2.1-PS.2.3]
  pageRef: /pages/week-2-newtons-laws/ps-2-1-worked-example-sliding-block
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 70
- identifier: 8ccbac1b-73cb-9336-f306-7bd24cd30b21
  name: Problem Set 2
  pageRef: /pages/week-2-newtons-laws/problem-set-2
  parent: cf6d9ae8-5d7b-6e78-8f1e-70cf24afc329
  weight: 80
- identifier: 467e5a37-cf4f-277f-b9e3-1ec984e101a8
  name: Week 3 Introduction
  pageRef: /pages/week-3-circular-motion/week-3-introduction
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 10
- identifier: b3916d89-3c89-2c76-6d33-7a22583b3bcb
  name: 'Lesson 8: Circular Motion - Position and Velocity [8.1-8.3]'
  pageRef: /pages/week-3-circular-motion/8-1-polar-coordinates
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 20
- identifier: dfa7cfb2-5de4-0721-4c7b-99d451dc900f
  name: 'Lesson 9: Uniform Circular Motion [9.1-9.3]'
  pageRef: /pages/week-3-circular-motion/9-1-uniform-circular-motion
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 30
- identifier: fc4bb7fe-8852-f18e-d0a7-cc1c4ea5e402
  name: "Lesson 10: Circular Motion \u2013 Acceleration [10.1-10.4]"
  pageRef: /pages/week-3-circular-motion/10-1-circular-motion-2013-acceleration
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 40
- identifier: 7e23662a-3078-b1c8-b4f5-1d9c948bab03
  name: 'Lesson 11: Newton''s 2nd Law and Circular Motion [11.1-11.3]'
  pageRef: /pages/week-3-circular-motion/11-1-newtons-2nd-law-and-circular-motion
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 50
- identifier: 938ca53b-e5be-db20-7d92-fe94493d1b80
  name: Week 3 Worked Example
  pageRef: /pages/week-3-circular-motion/PS-3-1-worked-example-orbital-circular-motion
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 60
- identifier: b4856988-2d63-2e38-e951-e3761d791ad5
  name: Problem Set 3
  pageRef: /pages/week-3-circular-motion/problem-set-3
  parent: 3c7d357c-bb95-e729-679b-539d23714ede
  weight: 70
- identifier: e7847b2b-6f8e-fc5e-d22d-745b96a68bd1
  name: Week 4 Introduction
  pageRef: /pages/week-4-drag-forces-constraints-and-continuous-systems/week-4-introduction
  parent: 919a2c50-6eb4-551d-940b-b0dbab2356f0
  weight: 10
- identifier: 05c9879c-c910-2f5c-b8c2-37c856cafd97
  name: 'Lesson 12: Pulleys and Constraints [12.1-12.5]'
  pageRef: /pages/week-4-drag-forces-constraints-and-continuous-systems/12-1-pulley-problems-part-i-set-up-the-equations
  parent: 919a2c50-6eb4-551d-940b-b0dbab2356f0
  weight: 20
- identifier: 869e8587-bad0-5bba-6781-da19b701a57a
  name: 'Lesson 13: Massive Rope [13.1-13.6]'
  pageRef: /pages/week-4-drag-forces-constraints-and-continuous-systems/13-1-rope-hanging-between-trees
  parent: 919a2c50-6eb4-551d-940b-b0dbab2356f0
  weight: 30
- identifier: b0dfeda3-e8e0-1b02-c85d-7aaa620c1e61
  name: 'Lesson 14: Resistive Forces [14.1-14.3]'
  pageRef: /pages/week-4-drag-forces-constraints-and-continuous-systems/14-1-intro-to-resistive-forces
  parent: 919a2c50-6eb4-551d-940b-b0dbab2356f0
  weight: 40
- identifier: b9bf868d-daf0-7c06-6058-0d06be825a09
  name: Problem Set 4
  pageRef: /pages/week-4-drag-forces-constraints-and-continuous-systems/problem-set-4
  parent: 919a2c50-6eb4-551d-940b-b0dbab2356f0
  weight: 50
- identifier: 7a7ef11d-6a6a-fd90-c8ba-c360dbead3ef
  name: Week 5 Introduction
  pageRef: /pages/week-5-momentum-and-impulse/week-5-introduction
  parent: c1168b62-a27d-cf9f-3fe2-550af1ed72f5
  weight: 10
- identifier: 82d8bb71-3390-c984-2d1c-66e939cfdfdd
  name: 'Lesson 15: Momentum and Impulse [15.1-15.5]'
  pageRef: /pages/week-5-momentum-and-impulse/15-1-momentum-and-impulse
  parent: c1168b62-a27d-cf9f-3fe2-550af1ed72f5
  weight: 20
- identifier: d890544a-61a8-d57d-7198-5f863dce020b
  name: 'Lesson 16: Conservation of Momentum [16.1-16.2]'
  pageRef: /pages/week-5-momentum-and-impulse/16-1-conservation-of-momentum
  parent: c1168b62-a27d-cf9f-3fe2-550af1ed72f5
  weight: 30
- identifier: 656d7d88-3df9-7349-90b5-f657ebd9509a
  name: 'Lesson 17: Center of Mass and Motion [17.1-17.7]'
  pageRef: /pages/week-5-momentum-and-impulse/17-1-definition-of-the-center-of-mass
  parent: c1168b62-a27d-cf9f-3fe2-550af1ed72f5
  weight: 40
- identifier: ba6a17ec-2a64-e576-34b0-0dd9fd6b8ab2
  name: Problem Set 5
  pageRef: /pages/week-5-momentum-and-impulse/problem-set-5
  parent: c1168b62-a27d-cf9f-3fe2-550af1ed72f5
  weight: 50
- identifier: dfec0cde-8b95-f3b3-887f-48c1061ba97b
  name: Week 6 Introduction
  pageRef: /pages/week-6-continuous-mass-transfer/week-6-introduction
  parent: 28d93f13-f552-de72-9aab-415b7158be8e
  weight: 10
- identifier: d21cac06-a2c8-528a-b008-e17885bfbc08
  name: 'Lesson 18: Relative Velocity and Recoil [18.1-18.4]'
  pageRef: /pages/week-6-continuous-mass-transfer/18-1-relative-velocity
  parent: 28d93f13-f552-de72-9aab-415b7158be8e
  weight: 20
- identifier: 3f6e8996-2a82-6cca-515d-e0c4378dde38
  name: 'Lesson 19: Continuous Mass Transfer [19.1-19.7]'
  pageRef: /pages/week-6-continuous-mass-transfer/19-1-rocket-problem-1-set-up-the-problem
  parent: 28d93f13-f552-de72-9aab-415b7158be8e
  weight: 30
- identifier: ce8e09d4-807a-9422-57ee-603eabb68035
  name: Week 6 Worked Examples [PS.6.1-PS.6.2]
  pageRef: /pages/week-6-continuous-mass-transfer/ps-6-1-rocket-sled-problem
  parent: 28d93f13-f552-de72-9aab-415b7158be8e
  weight: 40
- identifier: e75cbe56-57dc-1b51-c934-c400a80d903c
  name: Problem Set 6
  pageRef: /pages/week-6-continuous-mass-transfer/problem-set-6
  parent: 28d93f13-f552-de72-9aab-415b7158be8e
  weight: 50
- identifier: 1e15ff1e-ed2c-3307-da56-70f4a7de584b
  name: Week 7 Introduction
  pageRef: /pages/week-7-kinetic-energy-and-work/week-7-introduction
  parent: 1099b766-7930-f7e5-1ccc-c80d63899c02
  weight: 10
- identifier: 134ce034-c409-79f8-36a7-214e6d16747e
  name: 'Lesson 20: Kinetic Energy and Work in 1D [20.1-20.6]'
  pageRef: /pages/week-7-kinetic-energy-and-work/20-1-kinetic-energy
  parent: 1099b766-7930-f7e5-1ccc-c80d63899c02
  weight: 20
- identifier: 53ee5853-0a49-21c2-adae-1adaaafb6510
  name: 'Lesson 21: Kinetic Energy and Work in 2D and 3D [21.1-21.6]'
  pageRef: /pages/week-7-kinetic-energy-and-work/21-1-scalar-product-properties
  parent: 1099b766-7930-f7e5-1ccc-c80d63899c02
  weight: 30
- identifier: 994114a0-d054-2ba9-aeff-ab95b4cf1e57
  name: 'Lesson 22: Conservative and Non-Conservative Forces [22.1-22.5]'
  pageRef: /pages/week-7-kinetic-energy-and-work/22-1-path-independence-gravity
  parent: 1099b766-7930-f7e5-1ccc-c80d63899c02
  weight: 40
- identifier: 1a85f658-a6b6-19d1-7082-201370c974dd
  name: Week 7 Worked Example
  pageRef: /pages/week-7-kinetic-energy-and-work/ps-7-1-worked-example-collision-and-sliding-on-a-rough-surface
  parent: 1099b766-7930-f7e5-1ccc-c80d63899c02
  weight: 50
- identifier: 198483cf-4835-3e5d-6a38-5333ab778504
  name: Problem Set 7
  pageRef: /pages/week-7-kinetic-energy-and-work/problem-set-7
  parent: 1099b766-7930-f7e5-1ccc-c80d63899c02
  weight: 60
- identifier: fcdd8dba-5c17-3c15-30e4-4947500174b8
  name: Week 8 Introduction
  pageRef: /pages/week-8-potential-energy-and-energy-conservation/week-8-introduction
  parent: 13949981-43ef-cc49-3f7c-98265cfbd3ae
  weight: 10
- identifier: c5aafac6-88d5-4821-6aa8-5009455c4c24
  name: 'Lesson 23: Potential Energy [23.1-23.5]'
  pageRef: /pages/week-8-potential-energy-and-energy-conservation/23-1-introduction-to-potential-energy
  parent: 13949981-43ef-cc49-3f7c-98265cfbd3ae
  weight: 20
- identifier: 62e5f5c1-a360-761e-cc39-c63c99de3ea7
  name: 'Lesson 24: Conservation of Energy [24.1-24.4]'
  pageRef: /pages/week-8-potential-energy-and-energy-conservation/24-1-mechanical-energy-and-energy-conservation
  parent: 13949981-43ef-cc49-3f7c-98265cfbd3ae
  weight: 30
- identifier: 7764cf48-40ca-6295-a596-52406638f492
  name: 'Lesson 25: Potential Energy Diagrams [25.1-25.3]'
  pageRef: /pages/week-8-potential-energy-and-energy-conservation/25-1-force-is-the-derivative-of-potential
  parent: 13949981-43ef-cc49-3f7c-98265cfbd3ae
  weight: 40
- identifier: 3803dba0-0e2e-651a-5c14-95e6d8faab40
  name: Problem Set 8
  pageRef: /pages/week-8-potential-energy-and-energy-conservation/problem-set-8
  parent: 13949981-43ef-cc49-3f7c-98265cfbd3ae
  weight: 50
- identifier: b4cadb97-94c4-8f08-1f79-8ea3f224e263
  name: Week 9 Introduction
  pageRef: /pages/week-9-collision-theory/week-9-introduction
  parent: bc33ee80-c8fd-90e4-dfda-7092ddd24879
  weight: 10
- identifier: 18f46ffb-be76-a46e-9780-65aa344ceef1
  name: 'Lesson 26: Types of Collision [26.1-26.3]'
  pageRef: /pages/week-9-collision-theory/26-1-momentum-in-collisions
  parent: bc33ee80-c8fd-90e4-dfda-7092ddd24879
  weight: 20
- identifier: 81ee9da3-5071-cf42-2165-0926ad929f14
  name: 'Lesson 27: Elastic Collisions [27.1-27.6]'
  pageRef: /pages/week-9-collision-theory/27-1-worked-example-elastic-1d-collision
  parent: bc33ee80-c8fd-90e4-dfda-7092ddd24879
  weight: 30
- identifier: 07d691dc-35df-da5c-b795-db9825432f91
  name: 'Deep Dive: Center of Mass Reference Frame [DD.2.1-DD.2.7]'
  pageRef: /pages/week-9-collision-theory/dd-2-1-position-in-the-cm-frame
  parent: bc33ee80-c8fd-90e4-dfda-7092ddd24879
  weight: 40
- identifier: 40038e11-5d10-2264-d181-2356238564ec
  name: Problem Set 9
  pageRef: /pages/week-9-collision-theory/problem-set-9
  parent: bc33ee80-c8fd-90e4-dfda-7092ddd24879
  weight: 50
- identifier: 24520484-0767-1631-2e08-ec037e0da137
  name: Week 10 Introduction
  pageRef: /pages/week-10-rotational-motion/week-10-introduction
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 10
- identifier: 625a15e4-5ff0-83db-bb2e-81a6583103c5
  name: 'Lesson 28: Motion of a Rigid Body [28.1-28.3]'
  pageRef: /pages/week-10-rotational-motion/28-1-rigid-bodies
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 20
- identifier: b83ad997-5533-29c6-0233-437ea49e895d
  name: 'Lesson 29: Moment of Inertia [29.1-29.6]'
  pageRef: /pages/week-10-rotational-motion/29-1-kinetic-energy-of-rotation
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 30
- identifier: 016638c7-858e-4b42-d525-668d3166eba0
  name: 'Lesson 30: Torque [30.1-30.5]'
  pageRef: /pages/week-10-rotational-motion/30-1-introduction-to-torque-and-rotational-dynamics
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 40
- identifier: 8aeb3db6-4960-77bb-7575-8a2fd60b6c7f
  name: 'Lesson 31: Rotational Dynamics [31.1-31.7]'
  pageRef: /pages/week-10-rotational-motion/31-1-relationship-between-torque-and-angular-acceleration
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 50
- identifier: 1ea17804-f861-7e6c-0bce-e9e83c087d94
  name: Week 10 Worked Example
  pageRef: /pages/week-10-rotational-motion/ps-10-1-blocks-and-massive-pulley
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 60
- identifier: 4cc15f43-3fd8-2d72-4dc9-a100b00d26e6
  name: Problem Set 10
  pageRef: /pages/week-10-rotational-motion/problem-set-10
  parent: 146d8dd7-7c99-bbaf-ceb8-ed10af8bee47
  weight: 70
- identifier: 5e792911-b6e1-ef7b-9df6-e601cddc19bb
  name: Week 11 Introduction
  pageRef: /pages/week-11-angular-momentum/week-11-introduction
  parent: d36579bd-7dfc-b71f-7617-8b4b8d45c312
  weight: 10
- identifier: 432d416e-7880-ce79-80b5-07f7884c036e
  name: 'Lesson 32: Angular Momentum of a Point Particle [32.1-32.4]'
  pageRef: /pages/week-11-angular-momentum/32-1-angular-momentum-for-a-point-particle
  parent: d36579bd-7dfc-b71f-7617-8b4b8d45c312
  weight: 20
- identifier: 4dda04ab-f172-a544-1f39-111d35ef45b3
  name: 'Lesson 33: Angular Momentum of a Rigid Body [33.1-33.5]'
  pageRef: /pages/week-11-angular-momentum/33-1-worked-example-angular-momentum-of-2-rotating-point-particles
  parent: d36579bd-7dfc-b71f-7617-8b4b8d45c312
  weight: 30
- identifier: 764c8090-e1bb-ac38-6446-3719891094c3
  name: 'Lesson 34: Torque and Angular Impulse [34.1-34.5]'
  pageRef: /pages/week-11-angular-momentum/34-1-torque-causes-angular-momentum-to-change-point-particle
  parent: d36579bd-7dfc-b71f-7617-8b4b8d45c312
  weight: 40
- identifier: b8ea2fe1-fcf0-283a-b156-028db7d562eb
  name: Problem Set 11
  pageRef: /pages/week-11-angular-momentum/problem-set-11
  parent: d36579bd-7dfc-b71f-7617-8b4b8d45c312
  weight: 50
- identifier: f5a711f7-cf08-1504-228a-556ad3f8eade
  name: Week 12 Introduction
  pageRef: /pages/week-12-rotations-and-translation-rolling/week-12-introduction
  parent: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  weight: 10
- identifier: 5971c4ae-fc28-7ba1-62ff-58e6c76576b4
  name: 'Lesson 35: Rolling Kinematics [35.1-35.5]'
  pageRef: /pages/week-12-rotations-and-translation-rolling/35-1-translation-and-rotation-of-a-wheel
  parent: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  weight: 20
- identifier: ee20a48f-3d82-3723-cbbe-56ea037659af
  name: 'Lesson 36: Rolling Dynamics [36.1-36.5]'
  pageRef: /pages/week-12-rotations-and-translation-rolling/36-1-friction-on-a-rolling-wheel
  parent: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  weight: 30
- identifier: 34137618-411d-4427-e914-e646a3f7f568
  name: 'Lesson 37: Rolling Kinetic Energy & Angular Momentum [37.1-37.4]'
  pageRef: /pages/week-12-rotations-and-translation-rolling/37-1-kinetic-energy-of-translation-and-rotation
  parent: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  weight: 40
- identifier: d1c38e53-0c20-d699-f2e8-3e7f0242c713
  name: 'Deep Dive: Gyroscopes [DD.3.1-DD.3.3]'
  pageRef: /pages/week-12-rotations-and-translation-rolling/dd-3-1-gyroscopes-1-free-body-diagrams-torque-and-rotating-vectors
  parent: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  weight: 50
- identifier: 7a5814a4-20a1-f456-5d0d-f5ef0b30c31d
  name: Problem Set 12
  pageRef: /pages/week-12-rotations-and-translation-rolling/problem-set-12
  parent: fbf76190-d89e-eed2-930e-51f9ac3bf2a6
  weight: 60
- identifier: 3f40865d-76f5-ca49-063d-b063121a5ffc
  name: problem-set-1
  pageRef: /pages/week-1-kinematics/ps.1.1-three-questions-before-starting/problem-set-1
  parent: ee2f73c8-bddd-e169-e39c-a455f12469aa
  weight: 10
